# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - scaled_joint_trajectory_controller
    - robotiq_gripper_controller

  scaled_joint_trajectory_controller:
    type: FollowJointTrajectory
    joints:
      - UR5_shoulder_pan_joint
      - UR5_shoulder_lift_joint
      - UR5_elbow_joint
      - UR5_wrist_1_joint
      - UR5_wrist_2_joint
      - UR5_wrist_3_joint
    action_ns: follow_joint_trajectory
    default: true
  robotiq_gripper_controller:
    type: GripperCommand
    joints:
      - UR5_robotiq_85_left_knuckle_joint
    action_ns: gripper_cmd
    default: true